"""Added auction_team table

Revision ID: 2929155ef1d9
Revises: 96923fc1f541
Create Date: 2022-07-22 21:06:13.706670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2929155ef1d9'
down_revision = '96923fc1f541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('creation_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'tournament_id'),
    sa.UniqueConstraint('team_name', 'tournament_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_team')
    # ### end Alembic commands ###
