"""added match

Revision ID: 53655ffd2d78
Revises: b1f8e28c2980
Create Date: 2022-07-23 14:44:22.053129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53655ffd2d78'
down_revision = 'b1f8e28c2980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('start_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('match_num', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
