"""Added tournament table

Revision ID: 96923fc1f541
Revises:
Create Date: 2022-07-22 20:38:26.174183

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '96923fc1f541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('series_id', sa.VARCHAR(), nullable=False),
    sa.Column('channel_id', sa.VARCHAR(), nullable=False),
    sa.Column('doc_name', sa.VARCHAR(), nullable=False),
    sa.Column('points_sheet_name', sa.VARCHAR(), nullable=False),
    sa.Column('bidding_sheet_name', sa.VARCHAR(), nullable=False),
    sa.Column('team_points_name', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('creation_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament')
    # ### end Alembic commands ###
