"""added user_team_player

Revision ID: b1f8e28c2980
Revises: 3c5e45f9135a
Create Date: 2022-07-23 12:50:12.343486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f8e28c2980'
down_revision = '3c5e45f9135a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_team_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('user_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['user_team_id'], ['user_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_team_player')
    # ### end Alembic commands ###
