"""added playing_team and association

Revision ID: d7e9d7ef5247
Revises: 65b0fe411164
Create Date: 2022-07-23 10:35:23.769707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e9d7ef5247'
down_revision = '65b0fe411164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbrev', sa.String(), nullable=False),
    sa.Column('creation_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbrev'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament_playing_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('playing_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playing_team_id'], ['playing_team.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_playing_team')
    op.drop_table('playing_team')
    # ### end Alembic commands ###
